### ISSUE TITLE
文件链接打不开

### ISSUE THREAD

**Issue by Dionysen** [fengxue-jrql/termux-zink-backup-package#1]
文件分享链接打开是空白，请问能重新发一个嘛

**Comment by fengxue-jrql** [comment]
微云文件分享:backup.tar.xz下载地址:https://share.weiyun.com/hlTOhXwt文件大小:245.6M
if you want use zink virgl_vtest for linux deploy
微云文件分享:termux-backup-virgl_vtest-for-linuxdeploy.tar.gz下载地址:https://share.weiyun.com/DCdD3ydo文件大小:306.2M

**Comment by fengxue-jrql** [comment]
This link can be used in Chinese Mainland

**Comment by Dionysen** [comment]
This link shows that it has been deleted, but thank you anyway!

**Comment by Dionysen** [comment]
> 微云文件分享:backup.tar.xz下载地址:[https://share.weiyun.com/hlTOhXwt文件大小:245.6M](https://share.weiyun.com/hlTOhXwt%E6%96%87%E4%BB%B6%E5%A4%A7%E5%B0%8F:245.6M) if you want use zink virgl_vtest for linux deploy 微云文件分享:termux-backup-virgl_vtest-for-linuxdeploy.tar.gz下载地址:[https://share.weiyun.com/DCdD3ydo文件大小:306.2M](https://share.weiyun.com/DCdD3ydo%E6%96%87%E4%BB%B6%E5%A4%A7%E5%B0%8F:306.2M)

This link shows that it has been deleted, but thank you anyway!
